.TH AUTH2 7
.SH NAME
auth2 \- certificate authority service
.SH SYNOPSIS
.B auth2
.SH DESCRIPTION
.P
Listens to following paths:
.IP /jwt
responds with a JWT parametrized by the environment variables.
.IP /certs
reponds with a list of the current certificates and allows creation of new ones.
.IP /cert
returns a new certificate for a post request with cert name and password provided as form data.
.P
By default, the systemd unit defined in
.I /lib/systemd/system/auth2.service
reads the environment variables from
.IR /etc/auth2/env .
.SH OPTIONS
See
.IR /etc/auth2/env .
